# Generated by Django 3.2.8 on 2025-07-24 17:53

from django.db import migrations, models
import django.db.models.deletion
import wxcloudrun.models


class Migration(migrations.Migration):

    dependencies = [
        ('wxcloudrun', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WxUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(max_length=100, unique=True, verbose_name='微信openid')),
                ('nickname', models.CharField(blank=True, max_length=100, null=True, verbose_name='昵称')),
                ('avatar_url', models.URLField(blank=True, null=True, verbose_name='头像URL')),
                ('gender', models.SmallIntegerField(choices=[(0, '未知'), (1, '男'), (2, '女')], default=0, verbose_name='性别')),
                ('session_key', models.CharField(blank=True, max_length=100, null=True, verbose_name='会话密钥')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='最后登录时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否活跃')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '微信用户',
                'verbose_name_plural': '微信用户',
                'db_table': 'wx_user',
            },
        ),
        migrations.AddField(
            model_name='note',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=wxcloudrun.models.note_attachment_path, verbose_name='附件'),
        ),
        migrations.AddField(
            model_name='note',
            name='attachment_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='附件名称'),
        ),
        migrations.AddField(
            model_name='note',
            name='attachment_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='附件类型'),
        ),
        migrations.AddField(
            model_name='note',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='wxcloudrun.wxuser', verbose_name='用户'),
        ),
    ]
